version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: poc
      POSTGRES_USER: poc_user
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build: ./backend/auth_service
    ports:
      - "8001:8001"
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql+asyncpg://poc_user:admin123@postgres:5432/poc
    depends_on:
      - redis
      - postgres
    env_file:
      - ./backend/auth_service/.env

  product-service:
    build: ./backend/product_service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql+asyncpg://poc_user:admin123@postgres:5432/poc
    depends_on:
      - postgres
    env_file:
      - ./backend/product_service/.env

  cart-service:
    build: ./backend/cart_service
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql+asyncpg://poc_user:admin123@postgres:5432/poc
      - PRODUCT_SERVICE_URL=http://product-service:8002
      - USER_SERVICE_URL=http://auth-service:8001
    depends_on:
      - postgres
      - product-service
      - auth-service
    env_file:
      - ./backend/cart_service/.env

  gateway:
    build: ./backend/gateway
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001
      - PRODUCT_SERVICE_URL=http://product-service:8002
      - CART_SERVICE_URL=http://cart-service:8003
    depends_on:
      - auth-service
      - product-service
      - cart-service
    env_file:
      - ./backend/gateway/.env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    env_file:
      - ./frontend/.env.local
    depends_on:
      - gateway

volumes:
  redis_data:
  postgres_data:
